baseURL = 'https://wcomnisky.github.io/'
languageCode = 'en-us'
title = 'wcomnisky-logbook'

theme        = "hugo-PaperMod"

paginate     = 10
publishDir = "public"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A living reminder of my memories and learnings"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "wcomnisky's logbook"
  # keywords = "homepage, blog"
  images = [""]

# [taxonomies]
#     category = "blog"
#     tag      = "tags"
#     series   = "series"

[languages]
  [languages.en]
    title = "wcomnisky-logbook"
    subtitle = "A living reminder of my memories and learnings"
    # keywords = "logbook, blog, memories, learnings"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    # [languages.en.params.logo]
    #   logoText = "4bes.nl-hugo"
    #   logoHomeLink = ""
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#   [[menu.main]]
#     identifier = "blog"
#     name       = "Blog"
#     url        = "posts"